# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-24 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharableContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Content ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=251)),
                ('snippet_data', models.TextField()),
            ],
            options={
                'db_table': 'sharable_content',
            },
        ),
    ]
